### ISSUE TITLE
Boombox Controller on Thunderstore

### ISSUE THREAD

**Issue by x753** [Koder-Teh/lc_ffmpeg#1]
Your package on Thunderstore has been taken down due to the difficulty in verifying the integrity of the ffmpeg executable that your Boombox Controller mod downloads. If you would like to fix this, please replace it with pre-built executables included with your package, or point towards a reputably maintained depot.

**Comment by Koder-Teh** [comment]
> Your package on Thunderstore has been taken down due to the difficulty in verifying the integrity of the ffmpeg executable that your Boombox Controller mod downloads. If you would like to fix this, please replace it with pre-built executables included with your package, or point towards a reputably maintained depot.

Hello, sorry for such a misunderstanding. I created a second git with a fork in the main ffmpeg project (https://github.com/Koder-Teh/FFmpeg). How can I unlock the mod?

**Comment by x753** [comment]
Pointing towards an executable in a repo you control that can be changed arbitrarily is the issue. Point towards an official distributor (https://www.gyan.dev/ffmpeg/builds/), include the .exe in your package, or verify that the file matches the hash of the original executable when downloading it.

You can DM @753 on Discord or continue to use GitHub to discuss this.

**Comment by x753** [comment]
https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-win64-gpl.zip would also be an acceptable URL to download from.

**Comment by x753** [comment]
You are free to upload the fixed version and it won't get taken down.

**Comment by x753** [comment]
The package is live at https://thunderstore.io/c/lethal-company/p/KoderTeh/Boombox_Controller/
Thanks for fixing it.
